config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # resources :instruments

  resources :instruments do

    resources :bookings, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create]
  end

  resources :bookings, only: [:index,:show ]
  resources :reviews, only: [ :show]
end




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :instrument
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, presence: true
  has_many_attached :photos
  has_many :reviews

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category,
  against: [ :name, :category ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :instruments
  has_many :reviews, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_instrument, only: [:new, :create]

  def index
    # @instrument = Booking.instrument
    @user = current_user
    @bookings = @user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.instrument = @instrument
    @booking.user = current_user

    if @booking.save!
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :instrument_id, :start_date, :end_date)
  end

  def set_instrument
    @instrument = Instrument.find(params[:instrument_id])
  end

  #def num_days_booked(start_date, end_date)
   # (end_date - start_date).to_i
  #end

  #def calculate_total_payment(num_days, daily_price)
    #num_days * daily_price
  #end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    if params[:query].present?
      @instruments = Instrument.search_by_name_and_category(params[:query])
    else
      @instruments = Instrument.all
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
    @review = Review.new
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
  end

  def update
    @instrument = Instrument.find(params[:id])
    if @instrument.update(instrument_params)
      redirect_to instrument_path(@instrument)
    else
      render :edit
    end
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    redirect_to instruments_path, status: :see_other
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :price, :description, :category, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @instruments = Instrument.all 
  end
end

app/controllers/reviews_controller.rb
 class ReviewsController < ApplicationController
  before_action :set_instrument, only: [:new, :create]

    def new
      @review = Review.new
    end

    def show
      @review = Review.find(params[:id])
    end

    def create
      @review = Review.new(review_params)
      @review.instrument = @instrument
      @review.user = current_user

      if @review.save!
        redirect_to @review, notice: 'Review was successfully created.'
      else
        render :new
      end
    end

    private

    def set_instrument
      @instrument = Instrument.find(params[:instrument_id])
    end

    def review_params
      params.require(:review).permit(:content)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div>
  <h2 id="bookings-title">Bookings & Instruments</h2>

  <div class="container py-5">
    <% @bookings.each do |booking| %>
    <div class= "card mt-4">
      <div class="row">

        <div class="col-md-4">
          <%= cl_image_tag booking.instrument.photos.first.key, width: 296, crop: :fill, class: "instrument-img img-fluid" %>
        </div>

        <div class="col-md-8">
          <p> <strong>Instrument: <%= booking.instrument.name %> </strong> </p>
          <p> Price: £ <%= booking.instrument.price %>/day</p>
          <p>Start Date: <%= booking.start_date %></p>
          <p>End Date: <%= booking.end_date %></p>
        </div>

      </div>
    </div>
    <% end %>
  </div>

</div>

<span> <%= link_to "Homepage", root_path, class: "button-green" %> </span>

<span>  <%= link_to "Back to list", instruments_path, class: "button-blue"  %> </span>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->
<div class="booking-form-container"> <!-- Add a container div -->
  <h1>Instrument Booking</h1>

  <div>
    <%= simple_form_for [@instrument, @booking] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "Submit Booking", class: "btn button-blue" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
 <div class="container">
        <h1>Booking Details</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">Instrument: <%= @booking.instrument.name %></p>
                <p class="card-text">Your booking is confirmed. Thank you!</p>
                <p class="card-text">User: <%= current_user.email %></p>
                <p class="card-text"> Booking Starts <%= @booking.start_date %></p>
                <p class="card-text"> Booking End <%= @booking.end_date %></p>

                <button id="goBackButton" class="btn btn-primary btn-sm">Go Back to Home</button>
            </div>
        </div>
    </div>

<br>



<%= link_to 'See all my bookings', bookings_path %>

app/views/instruments/edit.html.erb
<div class="container py-5">
<div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
    <div class="bg-white rounded p-3 shadow">
        <h3>Edit the instrument </h3>
        <div class="row">
        <div class="col-12">
            <%= simple_form_for @instrument do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.file_field :photo_url, class: 'form-control' %>
            <%= f.submit class: "btn button-blue mt-4" %>
            <% end %>
<br>
            <%= link_to 'Back to Instruments', edit_instrument_path(@instrument.id), class: 'btn btn-secondary' %>
        </div>
        </div>

app/views/instruments/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
      <%= form_tag instruments_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find an instrument"
        %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="container py-4">
  <div class="row">
    <% @instruments.each do |instrument|%>
      <div class="co-12 col-sm-6 col-md-4 mb-3">
        <div class="bg-white rounded shadow h-100">
          <%= link_to instrument_path(instrument), class:"text-decoration-none" do %>
            <% if instrument.photos.attached? %>
              <%= cl_image_tag instrument.photos.first.key, width: 296, crop: :fill, class: "instrument-img img-fluid" %>
            <% end %>
            <div class="p-2 rounded-bottom">
              <strong class="name-color"><%= instrument.name %></strong>
              <small class="text-muted">£<%= instrument.price %>/day</small>
            </div>
          <% end %>
        </div>
      </div>
    <% end  %>
  </div>
</div>

app/views/instruments/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new Instrument</h3>
        <div class="row">
          <div class="col-12">
            <%= simple_form_for @instrument do |f| %>

            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit class: "btn button-blue mt-2 mx-1" %> <%= link_to 'Back to Instruments', instruments_path, class: 'btn button-green mt-2 mx-2' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/instruments/show.html.erb
<div class="container mt-5">
  <div class="bg-white rounded p-3 shadow" style="min-height: 50vh">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6">
        <h1><%= @instrument.name %></h1>
        <small class="text-muted">£<%= @instrument.price %>/day</small>
        <div>
        <% if @instrument.photos.attached? %>
          <% @instrument.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
        <% end %>
        </div>
        <br>

        <div class="row justify-align-center">
          <div class="row justify-align-center" style="color: white; display: inline-block; width: 180px; height: 40px; margin-right: 18px;">
            <%= link_to "Back to list", instruments_path, class: "button-green" %>
          </div>

        </div>
      </div>

      <div class="col-12 col-lg-6">
        <div class="row justify-content-center">
          <h1>Description</h1>
          <p><%= @instrument.description %></p>
          <p>Native Instruments Komplete Kontrol A49 Midi Guitar</p>

          <div class="col-12 col-lg-3">
            <p>Daily</p>
            <p>£7.00/day</p>
          </div>

          <div class="col-12 col-lg-3">
            <p>7 Days +</p>
            <p>£4.00/day</p>
          </div>

          <div class="col-12 col-lg-3">
            <p>30 Days +</p>
            <p>£2.80/day</p>
          </div>
        </div>


         <div class="row justify-align-center" style="color: white; display: inline-block; width: 250px; height: 40px; margin-left:-35px; margin-top:35px;">
            <%= link_to 'Rent this instrument', new_instrument_booking_path(@instrument), class: "button-blue" %>
          </div>

          <div style="color: grey">
          <% if @instrument.reviews.blank? %>
            Be the first to leave a review for <%= @instrument.name %>
          <% else %>
            <% @instrument.reviews.each do |review| %>
              <p><%= review.content %></p>
            <% end %>
          <% end %>
          </div>


          <div>
          <%= simple_form_for([@instrument, @review]) do |f| %>
          <%= f.input :content %>
          <button type="button" class="btn btn-link"><%= f.button :submit %></button>
          <% end %>
          </div>


      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= render "shared/flashes" %>


    <%= yield %>
    <% if user_signed_in?  %>
      <% current_user.email %>
    <% end %>
    <%= render 'shared/footer' %> <!-- Render the footer partial -->
  </body>
</html>

app/views/pages/home.html.erb
<%# <%= image_tag "musicbox.png", alt: 'logo', class: "rounded-circle"  %>
<section>
<div class="speaker" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1506157786151-b8491531f063?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80');">
  <div class="speaker-info">
    <h1>Welcome to <strong>Music Box</strong>!</h1>
    <span id="btn-new"><%= link_to "List an Instrument", new_instrument_path, class: "button-blue list-instrument" %></span>
    <span id="btn-rent"><%= link_to "Rent your Instrument", instruments_path, class: "button-blue rent-instrument" %></span>
  </div>
</div>
</section>

<%# Make the music images boxes beneath the main banner %>
<section class="gallery-page">
<%# <h2 class="gallery-title">Our gallery of the instruments</h2> %>
<div class="wraper">
<div class="gallery">
<%# <div class="square-image-container"> %>
<%# <button class="gallery-modal-btn" data-micromodal-trigger="modal" data-index="0"> %>
    <%# <%= cl_image_tag "fvmod9gmyhojf0pliun3", alt: 'logo', class: "square-music-image" %>
    <%# <%= cl_image_tag "hnexogjtk799hepjxzaf", alt: 'logo', class: "square-music-image" %>
    <%# <%= cl_image_tag "mwweeeokn9c7o8lfr4rk", alt: 'logo', class: "square-music-image" %>
    <%# <%= cl_image_tag "vtwwwfjiozuzbmoi9eeq", alt: 'logo', class: "square-music-image" %>
    <%# <%= cl_image_tag "uavrpvuuqrb9fvbteypu", alt: 'logo', class: "square-music-image" %>
    <%# <%= cl_image_tag "ztq9rpmvamf4r6nx1ino", alt: 'logo', class: "square-music-image" %>
</div>
</div>
</div>
</section>

app/views/reviews/new.html.erb
<h1>Instrument Review</h1>

<div><%= simple_form_for [@instrument, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>
</div>

app/views/reviews/show.html.erb
<div class="container">
        <h1>Review Details</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">Instrument: <%= @review.instrument.name %></p>
                <p class="card-text">User: <%= current_user.email %></p>
                <p class="card-text"> Reviews <%= @review.content %></p>
                <%= link_to "Homepage", root_path, class: "btn btn-success" %>
            </div>
        </div>
    </div>

app/views/shared/_booking-form.html.erb
<h1>Instrument Booking</h1>

<%= simple_form_for [@instrument, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>

  <%= f.submit "Submit Booking", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="wide-footer">
  <div class="footer-content">
    <div class="footer-links">
      <ul class="centered-links">
        <li class="footer-link"><%= link_to "About Our Music Box", "#" %></li>
        <li class="footer-link" ><%= link_to "Our Mission", "#" %></li>
        <li class="footer-link"><%= link_to "Terms of Service", "#" %></li>
        <li class="footer-link"><%= link_to "Privacy Policy", "#" %></li>
        <li class="footer-link"><%= link_to "FAQs", "#" %></li>
        <!-- Add more links as needed -->
      </ul>
    </div>
    <div class="social-media-icons">
      <a href="https://en-gb.facebook.com/" class="social-icon facebook"></a>
      <a href="https://www.instagram.com/" class="social-icon twitter"></a>
      <a href="https://twitter.com/AqilKha85649229?t=9EfbomCuQ5VHKtmqKgzFcg&s=09" class="social-icon instagram"></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
   <%= image_tag "musicbox_blue.png", alt: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link colour-text" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_path, class: "nav-link colour-text " %>
        </li>
        <li class="nav-item">
          <%= link_to "List Item", new_instrument_path, class: "nav-link colour-text" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "music_profile.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_review-form.html.erb
<%= form_with(model: [instrument, Review.new]) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit "Submit Review" %>
  </div>
<% end %>